Repository bitsandbytes-foundation/bitsandbytes, pull requests merged in 2024-08, with the labels that each got.

#1300 Fix dequant 4bit
  bitsandbytes/backends/cpu_xpu_common.py
Labels: Intel Integration

#1299 Enable bitsandbytes packaging for ROCm
  .github/scripts/build-rocm.sh
  .github/workflows/python-package.yml
  CMakeLists.txt
  bitsandbytes/cextension.py
  csrc/kernels.hip
  csrc/ops_hip.cuh
  docs/source/installation.mdx
  tests/test_functional.py
Labels: AMD integration

#1292 Embedding4bit and Embedding8bit implementation
  bitsandbytes/nn/__init__.py
  bitsandbytes/nn/modules.py
  tests/test_modules.py
Labels: enhancement

#1318 Bugfix: Load correct nocublaslt library variant when BNB_CUDA_VERSION override is set
  bitsandbytes/cextension.py
  tests/test_cuda_setup_evaluator.py
Labels: bug, CUDA Setup

#1316 Initial support for ppc64le
  include/Portable.h
  include/SIMD.h
  include/Type.h
Labels: cross-platform
