Repository bitsandbytes-foundation/bitsandbytes, pull requests merged in 2024-02, with the labels that each got.

#876 minimal patch to fix Windows compilation issues
  csrc/cpu_ops.cpp
  csrc/kernels.cu
  csrc/ops.cuh
Labels: medium priority

#908 Cmake + workflows
  .github/workflows/cmake.yml
  CMakeLists.txt
  docs/source/installation.mdx
  environment-bnb.yml
  include/SIMD.h
  setup.py
Labels: medium priority

#949 Make native code portable and add GitHub workflow for building
  .github/dependabot.yml
  .github/workflows/cmake.yml
  .github/workflows/python-package.yml
  CMakeLists.txt
  Makefile
  csrc/mps_kernels.metal
  csrc/mps_ops.h
  csrc/mps_ops.mm
  csrc/pythonInterface.cpp
  include/Algo-Direct-Common.h
  include/Algo-Direct2.h
  include/Portable.h
  include/SIMD.h
  include/Type.h
  pyproject.toml
  requirements-ci.txt
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: Windows, cross-platform, Linux, Mac, build, cicd

#414 Fix example int8_inference_huggingface.py
  examples/int8_inference_huggingface.py
Labels: high priority, Low Risk
