Repository bitsandbytes-foundation/bitsandbytes, pull requests merged in 2024-01, with the labels that each got.

#905 fix array index out of bounds in kgetColRowStats
  csrc/kernels.cu
Labels: bug, high priority, Low Risk

#922 Move to CPU before attempting to convert to numpy.
  bitsandbytes/utils.py
Labels: high priority, High Risk

#488 Added install requirements to setup
  setup.py
Labels: high priority, Low Risk

#944 Fix `max_memory` example on README
  README.md
Labels: documentation, medium priority, Low Risk

#873 fix library detection
  bitsandbytes/__main__.py
  bitsandbytes/cuda_setup/env_vars.py
  bitsandbytes/cuda_setup/main.py
  setup.py
Labels: high priority, CUDA_SETUP, Windows
