Repository bitsandbytes-foundation/bitsandbytes, pull requests merged in 2025-05, with the labels that each got.

#1539 ARM runners (faster than cross compilation qemu)
  .github/workflows/python-package.yml
Labels: Cross Platform, Linux, Build, aarch64

#1622 Linux aarch64 CI updates
  .github/scripts/auditwheel_show.py
  .github/scripts/build-cpu.sh
  .github/scripts/build-cuda.sh
  .github/workflows/python-package.yml
  .github/workflows/tests.yml
Labels: Cross Platform, Build, CI/CD, aarch64

#1623 Update compute_type_is_set attribute for Linear4bit
  bitsandbytes/nn/modules.py
Labels: Bug, Cross Platform

#1626 Moved int8_mm_dequant from CPU to default backend
  bitsandbytes/backends/cpu/ops.py
  bitsandbytes/backends/default/ops.py
Labels: Cross Platform

#1638 Switch CUDA builds to use Rocky Linux 8 container
  .github/scripts/build-cuda.sh
Labels: Build

#1636 Improvements to test suite
  .github/workflows/tests.yml
  tests/test_functional.py
  tests/test_ops.py
Labels: Cross Platform, CI/CD

#1639 Additional CI runners
  .github/workflows/tests.yml
Labels: CI/CD

#1647 Optimizer backwards compatibility fix
  bitsandbytes/optim/optimizer.py
Labels: Optimizers

#1644 Documentation Cleanup
  docs/source/_toctree.yml
  docs/source/algorithms.mdx
  docs/source/contributing.mdx
  docs/source/faqs.mdx
  docs/source/installation.mdx
  docs/source/non_cuda_backends.mdx
  docs/source/reference/functional.mdx
Labels: Documentation

#1628 Enable CPU/XPU native and ipex path
  bitsandbytes/__init__.py
  bitsandbytes/_ops.py
  bitsandbytes/autograd/_functions.py
  bitsandbytes/backends/cpu/ops.py
  bitsandbytes/backends/default/ops.py
  bitsandbytes/backends/utils.py
  bitsandbytes/backends/xpu/__init__.py
  bitsandbytes/backends/xpu/ops.py
  bitsandbytes/cextension.py
  bitsandbytes/functional.py
  bitsandbytes/nn/modules.py
  bitsandbytes/utils.py
  docs/source/installation.mdx
  tests/test_autograd.py
  tests/test_functional.py
  tests/test_linear4bit.py
  tests/test_modules.py
  tests/test_ops.py
Labels: Intel Integration, Cross Platform, x64 CPU
