Repository bitsandbytes-foundation/bitsandbytes, pull requests merged in 2025-04, with the labels that each got.

#1581 Fix torch.compile issue for LLM.int8() with threshold=0
  bitsandbytes/autograd/_functions.py
Labels: torch.compile

#1565 XPU backend support 8bit optimizer
  bitsandbytes/backends/cpu.py
  bitsandbytes/backends/cpu_xpu_common.py
  bitsandbytes/backends/cuda.py
  bitsandbytes/backends/mps.py
  bitsandbytes/backends/npu.py
  bitsandbytes/backends/xpu.py
  bitsandbytes/functional.py
  bitsandbytes/optim/optimizer.py
Labels: Intel Integration, Optimizers

#1592 HPU (Intel Gaudi) support for bitsandbytes
  bitsandbytes/__init__.py
  bitsandbytes/backends/hpu.py
  bitsandbytes/nn/modules.py
Labels: Intel Integration

#1594 Support LLM.int8() inference with torch.compile
  bitsandbytes/_ops.py
  bitsandbytes/autograd/_functions.py
  bitsandbytes/backends/cuda/ops.py
Labels: torch.compile

#1601 Updates for device agnosticism
  bitsandbytes/__init__.py
  bitsandbytes/autograd/_functions.py
  bitsandbytes/functional.py
  bitsandbytes/nn/modules.py
  pyproject.toml
  tests/helpers.py
  tests/test_autograd.py
  tests/test_functional.py
  tests/test_linear4bit.py
  tests/test_linear8bitlt.py
  tests/test_modules.py
  tests/test_ops.py
  tests/test_optim.py
Labels: cross-platform, cicd

#1605 Stop building for CUDA toolkit < 11.8
  .github/scripts/build-cuda.sh
  .github/workflows/python-package.yml
  CMakeLists.txt
  docs/source/installation.mdx
  install_cuda.py
  install_cuda.sh
Labels: build

#1613 fix intel cpu/xpu installation
  docs/source/installation.mdx
Labels: Documentation, Intel Integration

#1616 Support 4bit torch.compile fullgraph with PyTorch nightly
  bitsandbytes/nn/modules.py
Labels: torch.compile

#1617 Improve torch.compile support for int8 with torch>=2.8 nightly
  bitsandbytes/autograd/_functions.py
Labels: torch.compile

#1602 Add simple op implementations for CPU
  bitsandbytes/__init__.py
  bitsandbytes/backends/cpu/ops.py
  bitsandbytes/backends/cuda/ops.py
  bitsandbytes/backends/default/ops.py
  bitsandbytes/functional.py
  bitsandbytes/nn/modules.py
  tests/test_autograd.py
  tests/test_functional.py
  tests/test_linear4bit.py
  tests/test_linear8bitlt.py
  tests/test_modules.py
  tests/test_ops.py
Labels: Cross Platform, x64 CPU, aarch64

#1619 Set up nightly CI for unit tests
  .github/scripts/build-cuda.sh
  .github/workflows/tests.yml
  tests/test_functional.py
  tests/test_optim.py
Labels: CI/CD
