Repository bitsandbytes-foundation/bitsandbytes, pull requests merged in 2025-09, with the labels that each got.

#1679 Add SYCL Kernels for XPU backend
  .github/workflows/tests.yml
  CMakeLists.txt
  _typos.toml
  bitsandbytes/_ops.py
  bitsandbytes/autograd/_functions.py
  bitsandbytes/backends/cpu/ops.py
  bitsandbytes/backends/utils.py
  bitsandbytes/backends/xpu/__init__.py
  bitsandbytes/backends/xpu/ops.py
  bitsandbytes/cextension.py
  bitsandbytes/functional.py
  bitsandbytes/nn/modules.py
  bitsandbytes/utils.py
  csrc/pythonInterface.cpp
  csrc/xpu_kernels.cpp
  csrc/xpu_kernels.h
  csrc/xpu_ops.cpp
  csrc/xpu_ops.h
  docs/source/installation.mdx
  tests/test_functional.py
  tests/test_linear8bitlt.py
  tests/test_modules.py
  tests/test_ops.py
Labels: Intel

#1692 [XPU] Implemented 8bit optimizers in triton
  README.md
  bitsandbytes/backends/triton/kernels_4bit.py
  bitsandbytes/backends/triton/kernels_8bit_quant.py
  bitsandbytes/backends/triton/kernels_optim.py
  bitsandbytes/backends/triton/ops.py
  bitsandbytes/backends/xpu/ops.py
Labels: Intel, Optimizers

#1754 Bump minimum PyTorch to 2.3
  .github/workflows/tests.yml
  README.md
  bitsandbytes/autograd/_functions.py
  bitsandbytes/triton/triton_utils.py
  pyproject.toml
  tests/test_functional.py
Labels: CI/CD

#1746 [CUDA] Branchless NF4/FP4 kDequantizeBlockwise kernel for faster dequantization
  benchmarking/inference_benchmark.py
  csrc/kernels.cu
Labels: CUDA

#1758 Update log
  bitsandbytes/cextension.py
Labels: Intel, Optimizers

#1757 Add function to reverse 4bit weights for HPU
  bitsandbytes/backends/hpu/ops.py
Labels: Gaudi

#1766 Update workflow for packaging
  .github/scripts/build-cuda.sh
  .github/workflows/python-package.yml
Labels: Build, CI/CD

#1764 Add Thor support
  .github/scripts/build-cuda.sh
Labels: CUDA

#1770 Documentation updates for v0.48.0
  docs/source/installation.mdx
Labels: Documentation
