Repository bitsandbytes-foundation/bitsandbytes, pull requests merged in 2025-03, with the labels that each got.

#1549 Fix CPU dequantization to use nested dequantized scaling constant
  bitsandbytes/functional.py
Labels: bug, x64 CPU

#1547 Enable XPU int matmul
  bitsandbytes/backends/cpu_xpu_common.py
Labels: Intel Integration, cross-platform

#1544 PyTorch Custom Operator Integration
  bitsandbytes/__init__.py
  bitsandbytes/_ops.py
  bitsandbytes/autograd/_functions.py
  bitsandbytes/backends/__init__.py
  bitsandbytes/backends/cpu/__init__.py
  bitsandbytes/backends/cpu/ops.py
  bitsandbytes/backends/cuda/__init__.py
  bitsandbytes/backends/cuda/ops.py
  bitsandbytes/backends/default/__init__.py
  bitsandbytes/backends/default/ops.py
  bitsandbytes/cextension.py
  bitsandbytes/cuda_specs.py
  bitsandbytes/functional.py
  bitsandbytes/nn/modules.py
  csrc/kernels.cu
  csrc/kernels.cuh
  csrc/ops.cu
  csrc/ops.cuh
  csrc/pythonInterface.cpp
  docs/source/installation.mdx
  examples/compile_inference.py
  pyproject.toml
  tests/helpers.py
  tests/test_autograd.py
  tests/test_deprecated.py
  tests/test_functional.py
  tests/test_linear8bitlt.py
  tests/test_ops.py
Labels: high priority, cross-platform

#1575 Bump CUDA 12.8.0 build to CUDA 12.8.1
  .github/workflows/python-package.yml
Labels: build, chore

#1574 Drop Python 3.8 support.
  .github/workflows/python-package.yml
  .pre-commit-config.yaml
  benchmarking/int8/int8_benchmark.py
  benchmarking/matmul_benchmark.py
  bitsandbytes/_ops.py
  bitsandbytes/autograd/_functions.py
  bitsandbytes/backends/cpu/ops.py
  bitsandbytes/backends/cuda/ops.py
  bitsandbytes/cuda_specs.py
  bitsandbytes/diagnostics/cuda.py
  bitsandbytes/functional.py
  bitsandbytes/nn/modules.py
  bitsandbytes/optim/ademamix.py
  bitsandbytes/optim/optimizer.py
  bitsandbytes/triton/matmul_perf_model.py
  bitsandbytes/utils.py
  examples/int8_inference_huggingface.py
  pyproject.toml
  tests/helpers.py
  tests/test_functional.py
Labels: chore

#1576 Test cleanup
  benchmarking/optimizer_benchmark.py
  bitsandbytes/functional.py
  bitsandbytes/optim/adam.py
  pyproject.toml
  tests/conftest.py
  tests/test_autograd.py
  tests/test_deprecated.py
  tests/test_functional.py
  tests/test_generation.py
  tests/test_ops.py
  tests/test_optim.py
  tests/test_triton.py
Labels: cicd
