Repository bitsandbytes-foundation/bitsandbytes, pull requests merged in 2025-01, with the labels that each got.

#1458 cleanup: remove unused kernels/C++ code
  csrc/kernels.cu
  csrc/ops.cu
Labels: Low Risk

#1459 (Deps) Require torch 2.x and minor updates
  docs/source/installation.mdx
  pyproject.toml
Labels: dependencies

#1481 Initial support blackwell
  .github/scripts/build-cuda.sh
  CHANGELOG.md
  CMakeLists.txt
Labels: build

#1486 Exclude tests from distribution
  pyproject.toml
Labels: build

#1484 Enable dequant+matmul 8bit path for Intel CPU and XPU
  bitsandbytes/autograd/_functions.py
Labels: Intel Integration

#1489 add xpu device index for `Int8Params`
  bitsandbytes/nn/modules.py
Labels: Intel Integration
