Repository bitsandbytes-foundation/bitsandbytes, pull requests merged in 2025-06, with the labels that each got.

#1667 Add CPU + IPEX to nightly CI
  .github/workflows/tests.yml
  tests/test_linear8bitlt.py
Labels: CI/CD, x64 CPU

#1665 Fix params4bit passing bnb quantized
  bitsandbytes/nn/modules.py
Labels: Low Risk

#1669 Deprecation cleanup
  bitsandbytes/functional.py
  csrc/kernels.cu
  csrc/kernels.cuh
  csrc/ops.cu
  csrc/ops.cuh
  csrc/pythonInterface.cpp
  tests/test_deprecated.py
  tests/test_functional.py
  tests/test_modules.py
  tests/test_optim.py
Labels: Chore

#1670 CI workflow: bump torch 2.7.0 to 2.7.1
  .github/workflows/tests.yml
Labels: CI/CD

#1662 Add support for Intel Gaudi/HPU backend
  bitsandbytes/__init__.py
  bitsandbytes/autograd/_functions.py
  bitsandbytes/backends/hpu/__init__.py
  bitsandbytes/backends/hpu/ops.py
  bitsandbytes/backends/utils.py
  bitsandbytes/nn/modules.py
Labels: Intel Integration

#1629 [Triton/XPU] Support 4bit dequantization logic on Triton
  bitsandbytes/backends/triton/__init__.py
  bitsandbytes/backends/triton/ops.py
  bitsandbytes/backends/triton/triton_kernels.py
  bitsandbytes/backends/utils.py
  bitsandbytes/backends/xpu/ops.py
  bitsandbytes/nn/modules.py
  tests/test_functional.py
  tests/test_ops.py
Labels: Intel, Cross Platform

#1660 doc fix signature for 8-bit optim
  bitsandbytes/optim/adam.py
  bitsandbytes/optim/adamw.py
Labels: Optimizers

#1678 Apply clang-format rules
  csrc/common.cpp
  csrc/common.cuh
  csrc/common.h
  csrc/cpu_ops.cpp
  csrc/cpu_ops.h
  csrc/kernels.cu
  csrc/kernels.cuh
  csrc/mps_ops.mm
  csrc/ops.cu
  csrc/ops.cuh
  csrc/pythonInterface.cpp
Labels: Chore

#1683 Enable ROCm backend with custom ops integration
  .github/scripts/build-rocm.sh
  .github/workflows/python-package.yml
  CMakeLists.txt
  bitsandbytes/backends/cuda/ops.py
  bitsandbytes/cextension.py
  bitsandbytes/cuda_specs.py
  bitsandbytes/diagnostics/cuda.py
  bitsandbytes/diagnostics/main.py
  bitsandbytes/functional.py
  bitsandbytes/nn/modules.py
  csrc/common_hip.cuh
  csrc/kernels.hip
  csrc/kernels_hip.cuh
  csrc/ops.hip
  csrc/ops_hip.cuh
  csrc/pythonInterface.cpp
  tests/helpers.py
  tests/test_cuda_setup_evaluator.py
  tests/test_functional.py
  tests/test_linear4bit.py
  tests/test_ops.py
Labels: ROCm

#1687 Make minor improvements to optimizer.py
  bitsandbytes/optim/optimizer.py
Labels: Low Risk, Optimizers

#1689 Add CUDA 12.9 build
  .github/scripts/build-cuda.sh
  .github/workflows/python-package.yml
  .github/workflows/tests.yml
Labels: Build, CI/CD, Chore
