Repository bitsandbytes-foundation/bitsandbytes, pull requests merged in 2025-07, with the labels that each got.

#1693 CI: Test with PyTorch 2.8.0 RC
  .github/workflows/tests.yml
Labels: CI/CD

#1512 Automatically call CMake as part of PEP 517 build
  MANIFEST.in
  pyproject.toml
  setup.py
Labels: High Priority, Build

#1694 Cherry picks for v0.46.1 patch release
  .github/scripts/build-cuda.sh
  .github/workflows/python-package.yml
  .github/workflows/tests.yml
  MANIFEST.in
  bitsandbytes/nn/modules.py
  bitsandbytes/optim/adam.py
  bitsandbytes/optim/adamw.py
  bitsandbytes/optim/optimizer.py
  pyproject.toml
  setup.py
  tests/test_linear4bit.py
Labels: Build, CI/CD
